language: php

php:
    - 7.2
    - 7.3
    - 7.4

env:
    global:
        - COMPOSER_MEMORY_LIMIT=-1
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ] || [ "$TRAVIS_PHP_VERSION" == "7.3" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ] || [ "$TRAVIS_PHP_VERSION" == "7.3" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ] || [ "$TRAVIS_PHP_VERSION" == "7.3" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
